version: 2

dependencies:
  pre:
    - run: sudo apt update && sudo apt install cmake

jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Make build dir
          command: mkdir build
      - run:
          name: Make CMake files
          command: cd build && cmake ..
      - run:
          name: Get current dir
          command: pwd
