version: 2

jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - run:
        name: Install CMake
        command: sudo apt install cmake

workflows:
  version: 2

  deps_build:
    jobs:
      - build
