version: 2

machine:
  timezone:
    Europe/London
  environment:
    PATH: "/home/ubuntu/cmake-3.5.1-Linux-x86_64/bin:$PATH"

dependencies:
  cache_directories:
    - ~/cmake-3.5.1-Linux-x86_64
  override:
    - >
      if [ ! -d ~/cmake-3.5.1-Linux-x86_64 ]; then
        echo "No cache - building CMake"
        cd ~ && wget --quiet https://cmake.org/files/v3.6/cmake-3.5.1-Linux-x86_64.tar.gz && tar -xvf cmake-3.5.1-Linux-x86_64.tar.gz
      else
        echo "Cached CMake found"
      fi

jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Make build dir
          command: mkdir build
      - run:
          name: Make CMake files
          command: cd build && cmake ..
      - run:
          name: Get current dir
          command: pwd
